export const badgesSkeleton = [
  '<p align="center">',
  '  <img src="https://img.shields.io/badge/version-1.0.0-f59e0b?style=for-the-badge&logo=github" />',
  '  <img src="https://img.shields.io/badge/license-MIT-f43f5e?style=for-the-badge" />',
  '  <img src="https://img.shields.io/badge/language-TypeScript-ea580c?style=for-the-badge" />',
  '  <img src="https://img.shields.io/badge/stars-10k-fb923c?style=for-the-badge&logo=starship" />',
  '  <img src="https://img.shields.io/badge/PRs-welcome-ff69b4?style=for-the-badge" />',
  '</p>',
  '',
  '<p align="center">',
  '  <img src="https://img.shields.io/badge/build-passing-ef4444?style=flat-square" />',
  '  <img src="https://img.shields.io/badge/coverage-90%25-f97316?style=flat-square" />',
  '  <img src="https://img.shields.io/badge/dependencies-up_to_date-eab308?style=flat-square" />',
  '  <img src="https://img.shields.io/badge/platform-cross--platform-dc2626?style=flat-square" />',
  '  <img src="https://img.shields.io/badge/maintained-yes-ec4899?style=flat-square" />',
  '  <img src="https://img.shields.io/badge/contributors-50%2B-fdba74?style=flat-square" />',
  '  <img src="https://img.shields.io/badge/downloads-1M%2B-fda4af?style=flat-square" />',
  '  <img src="https://img.shields.io/badge/size-~5MB-fcd34d?style=flat-square" />',
  '</p>',
  '',
  '<h1 align="center">[项目名称]</h1>',
  '',
  '<p align="center">[项目标语，一句话定位]</p>',
  '',
  '---',
  '',
  '## 📖 项目简介',
  '',
  '- **背景**：[项目背景与动机]',
  '- **目标**：[项目核心目标]',
  '- **用户**：[目标用户群体]',
  '',
  '## 🚀 核心特性',
  '',
  '| 特性 | 说明 |',
  '|------|------|',
  '| ⚡ [特性名称] | [特性的详细说明] |',
  '| 🎯 [特性名称] | [特性的详细说明] |',
  '| 🔥 [特性名称] | [特性的详细说明] |',
  '| 💡 [特性名称] | [特性的详细说明] |',
  '| 🛡️ [特性名称] | [特性的详细说明] |',
  '',
  '<details>',
  '<summary><b>📋 详细功能</b></summary>',
  '',
  '<br>',
  '',
  '| 模块 | 说明 | 优先级 |',
  '|------|------|--------|',
  '| [模块名称] | [模块详细描述] | [优先级] |',
  '| [模块名称] | [模块详细描述] | [优先级] |',
  '| [模块名称] | [模块详细描述] | [优先级] |',
  '',
  '</details>',
  '',
  '## 🛠️ 技术栈',
  '',
  '| 技术 | 用途 |',
  '|------|------|',
  '| [技术名称] | [技术用途说明] |',
  '| [技术名称] | [技术用途说明] |',
  '| [技术名称] | [技术用途说明] |',
  '| [技术名称] | [技术用途说明] |',
  '',
  '## 📦 安装',
  '',
  '```bash',
  '[安装命令]',
  '```',
  '',
  '## 💻 快速开始',
  '',
  '```bash',
  '[基本使用示例]',
  '```',
  '',
  '[步骤说明]',
  '',
  '```bash',
  '[进阶使用示例]',
  '```',
  '',
  '[进阶说明]',
  '',
  '## ⚙️ 配置',
  '',
  '| 参数 | 说明 | 默认值 |',
  '|------|------|--------|',
  '| [参数名] | [说明] | [默认值] |',
  '| [参数名] | [说明] | [默认值] |',
  '| [参数名] | [说明] | [默认值] |',
  '',
  '## 📁 项目结构',
  '',
  '```',
  '[项目目录结构]',
  '```',
  '',
  '## 🤝 贡献指南',
  '',
  '[如何参与贡献]',
  '',
  '## 📄 许可证',
  '',
  'MIT © [作者]',
].join('\n');
