import type { TemplateValidationRules } from './validation';

export const neoMinimalRules: TemplateValidationRules = {
  mustContain: ['# ', '## ', '```'],
  forbidden: ['<div', '<p align', 'shields.io', '😄', '👍', '🎉', '🚀', '✨', '🔥'],
  maxPlaceholderResidue: 2,
  minLength: 400,
};

export const neoMinimalSkeleton = [
  '# [项目名称]',
  '',
  '> [一句话项目定位，英文或中英双语]',
  '',
  '![banner](https://via.placeholder.com/800x200)',
  '',
  '---',
  '',
  '## Features',
  '',
  '- **Tag 1** — [简短功能描述]',
  '- **Tag 2** — [简短功能描述]',
  '- **Tag 3** — [简短功能描述]',
  '- **Tag 4** — [简短功能描述]',
  '',
  '## Architecture',
  '',
  '```mermaid',
  'flowchart TD',
  '  A[Input] --> B[Module A]',
  '  B --> C[Module B]',
  '  C --> D[Output]',
  '```',
  '',
  '## Quick Start',
  '',
  '### Prerequisites',
  '',
  '- [Requirement 1]',
  '- [Requirement 2]',
  '',
  '### Installation',
  '',
  '```bash',
  '[install command]',
  '```',
  '',
  '### Usage',
  '',
  '```bash',
  '[usage example]',
  '```',
  '',
  '## API Reference',
  '',
  '### `functionName(args)`',
  '',
  '| Param | Type | Default | Description |',
  '|-------|------|---------|-------------|',
  '| `arg1` | `string` | — | [description] |',
  '| `arg2` | `number` | `10` | [description] |',
  '',
  '**Returns:** `Promise<Result>`',
  '',
  '## Project Structure',
  '',
  '```',
  '[directory tree]',
  '```',
  '',
  '## Contributing',
  '',
  'See [CONTRIBUTING.md](./CONTRIBUTING.md).',
  '',
  '## License',
  '',
  '[License] © [Author]',
].join('\n');
