import type { TemplateValidationRules } from './validation';

export const showcaseRules: TemplateValidationRules = {
  mustContain: [
    '<p align="center">',
    '<img',
    '## 💡 项目简介',
    '### ',
    '- [',
    '- [x]',
    '> ',
    '## 📄 许可证',
  ],
  forbidden: [
    '```markdown',
    '[项目简称 Banner',
    'via.placeholder.com',
  ],
  maxPlaceholderResidue: 3,
  minLength: 500,
};

export const showcaseSkeleton = [
  '<p align="center">',
  '  <img src="https://placehold.co/900x240/1a1a2e/e0e0e0?text=[项目简称 Banner]" alt="[项目名称] Banner" width="100%" />',
  '</p>',
  '',
  '<p align="center">',
  '  <img src="https://img.shields.io/badge/版本-1.0.0-8b5cf6?style=for-the-badge" />',
  '  <img src="https://img.shields.io/badge/许可-MIT-a855f7?style=for-the-badge" />',
  '  <img src="https://img.shields.io/badge/语言-TypeScript-7c3aed?style=for-the-badge" />',
  '  <img src="https://img.shields.io/badge/PRs-welcome-9333ea?style=for-the-badge" />',
  '</p>',
  '',
  '> [一句引语，关于项目愿景或理念]',
  '',
  '---',
  '',
  '## 💡 项目简介',
  '',
  '[叙事段落1：项目的缘起和故事]',
  '',
  '[叙事段落2：项目的发展和里程碑]',
  '',
  '[叙事段落3：项目的愿景和未来方向]',
  '',
  '---',
  '',
  '## ✨ 核心特性',
  '',
  '### 💡 [特性一名称]',
  '',
  '[特性一描述]',
  '',
  '### 💡 [特性二名称]',
  '',
  '[特性二描述]',
  '',
  '### 💡 [特性三名称]',
  '',
  '[特性三描述]',
  '',
  '### 💡 [特性四名称]',
  '',
  '[特性四描述]',
  '',
  '### 💡 [特性五名称]',
  '',
  '[特性五描述]',
  '',
  '---',
  '',
  '## 🛠️ 技术栈',
  '',
  '- **[技术一]** — [选择该技术的原因]',
  '- **[技术二]** — [选择该技术的原因]',
  '- **[技术三]** — [选择该技术的原因]',
  '',
  '---',
  '',
  '## ⚡ 安装',
  '',
  '> **前置要求**：[前置条件]',
  '',
  '```bash',
  '[安装命令]',
  '```',
  '',
  '---',
  '',
  '## 🚀 快速开始',
  '',
  '```bash',
  '[基本使用示例]',
  '```',
  '',
  '[说明]',
  '',
  '```bash',
  '[进阶使用示例]',
  '```',
  '',
  '[说明]',
  '',
  '---',
  '',
  '## 🗺️ 路线图',
  '',
  '- [ ] [规划中的功能 1]',
  '- [ ] [规划中的功能 2]',
  '- [ ] [规划中的功能 3]',
  '- [x] [已完成的功能]',
  '',
  '---',
  '',
  '## 🤝 贡献指南',
  '',
  '[如何参与贡献]',
  '',
  '---',
  '',
  '## 📄 许可证',
  '',
  'MIT © [作者]',
  '',
  '> [结束语，富有感染力的句子]',
].join('\n');
